Feature/add sdk documentation
bimdata/documentation pull request #34
Opened 2023-05-25 08:01 UTC by LrxGaelle

2023-05-25 08:11 UTC, Kurtil requested changes

2023-05-25 08:11 UTC, Kurtil commented on src/viewer/viewer_sdk.md
> +When going on [http://localhost:8080](http://localhost:8080), a simple interface will parse your projects and models and let you open the one you want.
=> a simple interface will let you open the project and model you want.

2023-05-25 08:11 UTC, Kurtil commented on src/viewer/viewer_sdk.md
> +This tool asks you a couple of questions about the plugin you develop and generate from your answers basic files for your plugin.
basic => boilerplate ?

2023-05-25 08:17 UTC, NicolasRichel requested changes

2023-05-25 08:17 UTC, NicolasRichel commented on src/.vuepress/components/Home.vue
>          <!-- <BIMDataCard>
You got some commented (dead?) code here.
Maybe it should be removed.

2023-05-25 08:17 UTC, NicolasRichel commented on src/viewer/viewer_sdk.md
> +First, you have to clone the sdk repo and install SDK dependecies :
Typo here: **dependecies**

2023-05-26 14:49 UTC, Kurtil approved these changes

2023-05-27 12:47 UTC, NicolasRichel approved these changes

2023-05-29 08:30 UTC, Amoki approved these changes

2023-05-30 06:48 UTC, amineau approved these changes

2023-05-30 07:37 UTC, merged