[WIP] viewer rework for v2
bimdata/documentation pull request #51
Opened 2024-02-20 15:33 UTC by Kurtil

2024-03-13 14:35 UTC, Amoki commented on src/viewer/reference/layout.md
> +
Add an example of a simple and a complex layout?

2024-03-13 14:37 UTC, Amoki commented on src/viewer/reference/mount.md
> +| `direction` | `string`               | "column" or "row"(**default**). The direction of the container.                 |
Add an example of a simple and a complex layout here?

2024-03-14 10:02 UTC, Amoki requested changes

2024-03-14 10:02 UTC, Amoki commented on src/viewer/README.md
> +[The UI can be customized](/viewer/customize_the_ui.html) to organize the workspace as you need and a flexible javascript API using [<svg class="logo" viewBox="0 0 128 128" width="18" height="18" dat
```suggestion
[The UI can be customized](/viewer/customize_the_ui.html) to organize the workspace as you need and a flexible javascript API using [<svg class="logo" viewBox="0 0 128 128" width="18" height="18" data-v-0495d436=""><path fill="#42b883" d="M78.8,10L64,35.4L49.2,10H0l64,110l64-110C128,10,78.8,10,78.8,10z" data-v-0495d436=""></path><path fill="#35495e" d="M78.8,10L64,35.4L49.2,10H25.6L64,76l38.4-66H78.8z" data-v-0495d436=""></path></svg> Vue.js 3](https://vuejs.org/) allows to create custom plugins to match your business perfectly.
However, you don't need to master Vue.js to develop a plugin and you can still update the DOM with jQuery if you like!
```

2024-03-14 16:24 UTC, Amoki approved these changes

2024-03-19 15:43 UTC, Amoki approved these changes

2024-03-20 11:05 UTC, NicolasRichel approved these changes

2024-03-20 11:08 UTC, merged